from src.handlers.start import register_start_command_handlers
from src.handlers.unknown import register_unknown_command_handlers

register_start_command_handlers()
register_unknown_command_handlers()
